### ISSUE TITLE
Getting "Error in HathiTrust AJAX call."

### ISSUE THREAD

**Issue by hadro** [ryanfb/book-aligner#8]
Not sure if that's a temporary problem, or what, but I love this tool and that error seems to be preventing it from working! :)

**Comment by ryanfb** [comment]
Thanks for the bug report! Is there any chance you could provide the following:

* Browser/OS
* URL string used
* Browser JavaSript console output

For when you're getting the error? I tried to replicate just now by using the example URLs from the landing page under Chrome on OS X, but didn't see any immediate issues that resulted in an error. Looking at the warnings it could be that a different browser handles mixed HTTP/HTTPS calls differently and generates an error now, so that will probably be the first place I look.

**Comment by hadro** [comment]
Aha, false alarm, it was Privacy Badger blocking the connection to the Hathi catalog -- apologies! Worked fine on this volume once I unclenched my privacy settings: 
https://babel.hathitrust.org/cgi/pt?id=mdp.39015085786880

(that said, that Hathi volume is in Google here: https://books.google.com/books?vid=UOM:39015085786880 , though that match didn't turn up, but maybe that's because it's a closed volume? Anyway, I think it's working as expected, and you can ignore my initial report...)

**Comment by ryanfb** [comment]
Thanks for checking! I'll look into seeing why that match isn't showing up - it may also be that I need to reindex everything, which I've been meaning to do for a while as I haven't done it since I first published this.
